#!/bin/bash

#Run this script after activating (workon) the virtual env.
PYVER=3.7

if [ -z "$VIRTUAL_ENV" ] ; then
    echo "You must activate your virtualenv: set '$VIRTUAL_ENV'"
    exit 1
fi

# Modify PYTHON_ROOT to point to your globally installed version of Python
PYTHON_ROOT="/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/$PYVER"
PYTHON_BINARY="bin/python$PYVER"
FRAMEWORK_PYTHON="$PYTHON_ROOT/$PYTHON_BINARY"

# Use the Framework Python to run the app
export PYTHONHOME=$VIRTUAL_ENV

echo "Using Python framework:" $FRAMEWORK_PYTHON
#echo "Using virtual environment:" $$VIRTUAL_ENV

# Turn on optimization
# Values:
# 0 = off
# 1 = on like -O
#   asserts are stripped
#   the generated bytecode files are using the .pyo extension instead of .pyc
#   sys.flags.optimize is set to 1
#   __debug__ is set to False
# 2 = on like -OO
#   everything 1 does
#   doctsrings are stripped.
export PYTHONOPTIMIZE=0

echo "Starting with..." "$FRAMEWORK_PYTHON -O" "$1"
exec "$FRAMEWORK_PYTHON" "$1"